package: cntnd
version: '0.0.1'
author: 'Thomas D Ascoli'
supportpage: https://github.com/cntnd/rdx.cntnd/issues
info: 'Modulsammlung'
compile: 0

page:
  title: 'translate:title'
  perm: modulsammlung[]
  icon: rex-icon fa-plus-square
  pjax: false
  subpages:
    module: {title: 'translate:module'}
    templates: {title: 'translate:templates'}
    info:
      title: 'Info'
      itemclass: 'pull-right'
      subpages:
        info: { title: 'Info'}
        moduluebersicht: { title: 'translate:moduluebersicht'}
        templateuebersicht: { title: 'translate:templateuebersicht'}
        changelog: { title: 'translate:changelog'}
        lizenz: { title: 'translate:lizenz'}